BUG!!! This version does not work. Connection check fail
Remember before you were have this bug when you loose data it would crash. Something is clearly wrong with that code and now you added a function using same code on launch and it broke everything. FIX IT! :) 

==================== PROD MODE ====================


NO DATA
NO DATA
Traceback (most recent call last):
  File "C:\Users\3YInferno\Documents\DEV\Python\PriceAlert\priceAlertX.py", line 148, in check_connection
    price=si.get_live_price(AAPL) #Check AAPL price available
NameError: name 'AAPL' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\3YInferno\Documents\DEV\Python\PriceAlert\priceAlertX.py", line 509, in <module>
    check_connection() #Make sure Yahoo data is available
  File "C:\Users\3YInferno\Documents\DEV\Python\PriceAlert\priceAlertX.py", line 154, in check_connection
    playsound('trendDownBig.wma')
  File "C:\Users\3YInferno\AppData\Local\Programs\Python\Python39\lib\site-packages\playsound.py", line 41, in _playsoundWin
    sleep(float(durationInMS) / 1000.0)